#!/bin/bash

verion_arg=$1

mc_versions="1.3.2 1.4.7 1.5.1 1.5.2 1.6.4 1.7.10 1.8.9 1.9.4 1.10.2 1.11.2 1.12.2 1.13.2"
echo "Available MC versions: ${mc_versions}"

while [ true ]; do

    if [ -z "${verion_arg}" ]; then
        echo -n "Enter the version you want to edit: "
        read version
    else
        version="${verion_arg}"
    fi
    unset verion_arg

    valid="F"
    for i in $mc_versions; do
        if [ "${i}" == "${version}" ]; then
            valid="T"
        fi
    done

    if [ "${valid}" == "F" ]; then
        echo "'${version}' is an invalid MC version!"
    else
        break
    fi
done

export MC_VERSION="${version}"
echo "Starting Gradle with MC version ${MC_VERSION}..."
./gradlew yarn
