name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        mc_version: [
          '1.3.2',
          '1.4.7',
          '1.5.2',
          '1.6.4',
          '1.7.10',
          '1.8',
          '1.8.9',
          '1.9.4',
          '1.10.2',
          '1.11.2',
          '1.12.2',
          '1.13.2'
        ]
    env: 
        MC_VERSION: ${{ matrix.mc_version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: ./gradlew build javadocJar checkMappings mapNamedJar unifyMappings --stacktrace
      - run: ./gradlew publishToMavenLocal unifyMappings --stacktrace
      - run: cd test-mod && ./gradlew build genSources
